### PR TITLE
Finish removing GUI features

### PR DESCRIPTION
**Pull request by izik1**
I tugged lightly at the code and all of this came with it _sighs_. Sorry for the single commit / hard to readness. The scope is a lot bigger than I originally thought it would be.

### CODE REVIEW

**Comment by izik1** [comment]
I seem to have broken searching, not sure how I did that. I also can't seem to get clang-format to output the same files that the Hygiene Checks want. (Going to go to sleep, been trying at this for longer tonight than I should have probably)

**Comment by izik1** [comment]
Redid the PR to fix all the broken stuff and to make the diff a bit nicer.

* Hygiene is failing because I have clang-format 9.0.0 whereas the hygiene checks use 8.9.4

* Windows is failing, not because of a bug I wrote, but because of one I seem to have exposed. the cygwin make (`Make_cyg_ming.mak`) doesn't build `iscgypty.c` into `iscgypty.o` which causes linker errors. I'm not sure if removing `iscgypty` is the correct option, or if it should be added back into the make file instead.

**Comment by bryphe** [comment]
Thanks for the help here, @izik1 ! This is great. Pretty massive code reduction 😄 

image

> Hygiene is failing because I have clang-format 9.0.0 whereas the hygiene checks use 8.9.4

We're using the `clang-format` NPM package on CI which looks like its at `clang-format 10.0.0` (the NPM package version is `1.3.0`: https://www.npmjs.com/package/clang-format). I can help with this part 👍 

> Windows is failing, not because of a bug I wrote, but because of one I seem to have exposed. the cygwin make (Make_cyg_ming.mak) doesn't build iscgypty.c into iscgypty.o which causes linker errors. I'm not sure if removing iscgypty is the correct option, or if it should be added back into the make file instead.

Ah, it looks like we need this line: 
```
OBJ += $(CUIOBJ)	
```
In `Make_cyg_ming.mak` - brought it back and built on Win, looks like it works now. 

I believe that we can remove this, though - this is only used on startup to check if we're in a Cygwin terminal (which shouldn't matter with `libvim`, since we're agnostic of the terminal!).

**Comment by bryphe** [comment]
All is green now - thanks @izik1 for removing all of this! 🎉

**Pull request merged**
