### PR TITLE
Feature: State machine for normal mode

### PR DESCRIPTION
**Pull request by bryphe**
__Issue:__ In normal mode, the flow is to block input - this creates an implicit tracking of the current state. For the onivim model, though, I'd like to have an inverted flow - a function of `(state, input) => state`.

__Fix:__ This necessitates changing the logic - instead of waiting for a key press, we need to switch to an event-driven model, and manage tracking state here.

### CODE REVIEW

**Comment by justinmk** [comment]
@bryphe wondering if you have seen [state.c](https://github.com/neovim/neovim/blob/master/src/nvim/state.c) in Nvim, which is a similar state-machine refactor of vim. I assume you don't want the baggage of Nvim CI or other decisions, but since you seem to be interested in refactoring vim...

**Comment by bryphe** [comment]
Hey, thanks @justinmk ! 

> I assume you don't want the baggage of Nvim CI or other decisions,

Ah, no - not a baggage thing at all - I would certainly prefer to use `nvim` and benefit from the refactoring you've already done! It's not easy...

> but since you seem to be interested in refactoring vim...

I'm not so interested in refactoring Vim, but I want a _pure functional Vim_  - where it behaves as a synchronous function of `(state, input) => new state`. This will simplify our architecture in Onivim 2 significantly. This part, I believe, would be doable in `nvim` though.

The challenge I had was to get `nvim` building in both the environments I need (Reason via `esy`, and `wasm`).  Primarily, the C++ dependencies were painful to get building there - the environment we use for building reason projects on Windows uses a cygwin + mingw cross-compiler environment that a lot of projects don't recognize or handle correctly, so it involves a lot of hacking to get them to build. 

I actually spent ~16 hours first with `nvim` trying to get it to build unsuccessfully - some of the deps had issues in that environment - I estimated it would take ~3-4 weeks for me to complete that work (either refactoring the codebase to remove those deps, or invest time in getting those deps building in `esy`). It can be unpredictable because as you fix issues you encounter further ones down the road. The C codebase happened to be much easier to get building in those environments, unfortunately.

We're actually going through a similar exercise with some other C++ libraries, like Skia, at the moment too (that has its own set of challenges...).

If there was a way I could magically build `nvim` in those environments (`esy` / `wasm`)  - I would switch to it for sure. (And aside from the purely technical benefits - you and the team have been incredibly helpful & supportive of Onivim, too!). If you have any ideas - let me know. (I think @jordwalke and @andreypopp are interested in this too).

**Comment by bryphe** [comment]
> Ah, that makes total sense. It was actually the original intention of tarruda's state-machine refactor. To be purely functional I guess one would need to remove all side-effects: logging, shell, output, ... For that, the UI externalization and "provider" efforts seem to help: all side-effects become events (which can be ignored). Then maybe we could consider externalizing things like logging, for this use-case.

Exactly! The model `(state, input) => new state` isn't entirely accurate, as you mentioned there'd be 'side effects' as a result of the input too - handling those as events would be great.

The work that Neovim has done in this refactoring is a great first step. Turns out that a lot of logic in Vim is conflated with being-a-terminal - so the externalization of things like command line are a very helpful step past that. So if it wasn't for the build integration issues, from a purely code / architecture perspective - it'd be much better to build on top of Neovim.

Regarding the build - I had problems with a few other dependencies, actually - even `libuv` and the lua deps were problematic in our`esy` environment. As an example, we have a `libuv` package for `esy` here that @andreypopp put together - https://github.com/esy-packages/libuv - but unfortunately it doesn't build on Windows last I tried.

> CMake is C++, but I think it can generate a build script on a separate system pretty easily?

It definitely can, and the `Makefile`'s it generates are sometimes OK, but sometimes not on Windows (if it doesn't accommodate that hybrid Cygwin + MingW cross-compiler environment, which was the case for some of those deps). . For example, some packages assume if you're using a MingW cross-compiler, you must be on Unix, etc. Some libs 'just work' and then some libs need a lot of `#ifdef` hacking. This is where the major time sink is for me in getting the dependencies to build in the environment we need. And it can be hard to predict how much time it will take. So it's something I'm actively trying to avoid 😄 

It's not an issue with Neovim IMO - the more modern choices of CMake, C++, and the dependencies make perfect sense - it happens that the OCaml / Reason build toolchain on Windows is somewhat non-standard. As a consequence, it's significantly easier to get a pure-C library building in `esy` cross-platform (to be used by a Reason / OCaml library) - at least today.

**Comment by justinmk** [comment]
> we have a `libuv` package for `esy` here that @andreypopp put together - https://github.com/esy-packages/libuv - but unfortunately it doesn't build on Windows last I tried.

Maybe esy could leverage [vcpkg](https://github.com/Microsoft/vcpkg) somehow, which is driving towards "deterministic" C-land dependencies. And they already have a libuv package.

**Comment by justinmk** [comment]
@andreypopp  https://github.com/esy-packages/libuv/blob/master/1.25.0.json#L6 seems to be using the old autoconf build for libuv. libuv now provides a CMake file, maybe it helps somehow: https://github.com/libuv/libuv/blob/v1.x/CMakeLists.txt

**Comment by bfredl** [comment]
>  even libuv

It sounds with your state machine model you even wouldn't use the libuv-based event loop, but rather keep event handling in oni layer, and feed keys into vim/nvim as they arrive from oni.  Though it could be that nvim is using libuv already in many places except for the main loop, so building a nvim without libuv is difficult.

>  and the lua deps were problematic in our esy environment.

I assume you mean the luarocks environment for building and testing nvim. At runtime, only lua-5.1 is needed, which should be very portable. I think it would be possible for us to generate a nvim source tree with all pregenerated sources, so luarocks env wouldn't be needed.

**Pull request merged**
